---

- name: Create basic kibana directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user_id }}"
    group: "{{ kibana_group_id }}"
  loop:
    - '{{ kibana_config_dir }}'
    - '/usr/share/kibana/data'

- name: Ensure Kibana config exists
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_config_dir }}/kibana.yml"
    owner: "{{ kibana_user_id }}"
    group: "{{ kibana_group_id }}"    